# Generated by Django 4.0.4 on 2022-05-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='type',
            field=models.CharField(choices=[('Business', 'Business'), ('Personal', 'Personal')], default='null', max_length=100, verbose_name='Type'),
        ),
    ]
