# Generated by Django 4.0.4 on 2022-05-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_created_by_alter_staff_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='modified_by',
        ),
    ]
