# Generated by Django 4.0.4 on 2022-05-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_staff_created_by_remove_staff_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=12, verbose_name='Gender'),
        ),
    ]
